version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
      - daphne
    links:
      - daphne
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/static

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data

  daphne:
    build: .
    image: "app:latest"
    working_dir: /app
    command: >
      sh -c "daphne -b 0.0.0.0 -p 9000 app.asgi:application"
    ports:
      - "9542:9542"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    links:
      - redis


volumes:
  postgres-data:
  static-data:
  redis-data: